### PR TITLE
Extensibility and Code base clean up / linting etc..

### PR DESCRIPTION
**Pull request by nmccready**
I was not planning on making a PR. But I thought I might as well try.

The major influence for forking and clean up PanelGroup.js was to have function inside the class which are reusable and more overridable. This will make extending PanelGroup without tons of copy pasta much much easier.

The versioning of 1.0.6-0 , was to make my life easier since I am pulling this package directly from my gitrepo. Therefore it can be reverted.

### CODE REVIEW

**Comment by nmccready** [comment]
trying to resolve travis now

**Comment by nmccready** [comment]
closing until resolved

**Comment by DanFessler** [comment]
I really appreciate the work you put into this.  I recently merged a lot of pull requests which has made the process of merging this one a bit painful, but i'm working my way through it.

**Comment by DanFessler** [comment]
Love the changes.  Thanks!

**Comment by nmccready** [comment]
Thank you!

**Comment by DanFessler** [comment]
@nmccready Turns out the npm build is broken due to your debug-fabulous being located outside of src I believe.  I also fundamentally dont understand how to use your package.  I'm going to roll back the debug-fabulous changes for now, and you can submit a fix if you'd like.  In the meanwhile, can you explain how it's intended to be used?

**Pull request merged**
