### PR TITLE
Added compatibility with React 16.

### LINKED ISSUE #10: Support React 16
Hello, @DanFessler!

Is there a plan to support React 16? The only _problem_ is the `React.createClass`. If you are OK with it, I'd submit a PR.

### PR DESCRIPTION
**Pull request by radekmie**
Fixes #10.

### CODE REVIEW

**Comment by radekmie** [comment]
Ping @DanFessler.

**Comment by radekmie** [comment]
Ping @DanFessler.

**Comment by tsneed290** [comment]
Can we merge in this PR please?

**Comment by DanFessler** [comment]
done.  Thanks for the PR

**Comment by tsneed290** [comment]
Please publish to NPM.

**Comment by radekmie** [comment]
Ping @DanFessler.

**Comment by radekmie** [comment]
Ping @DanFessler.

**Pull request merged**
